package webui

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/johndauphine/dmt/v5/internal/config"
	"github.com/johndauphine/dmt/v5/internal/logging"
)

// sessionCookie names the browser session cookie set after a successful login.
const sessionCookie = "dmt_webui_session"

// Login brute-force controls (#594). Deliberately lenient: a strong token is
// infeasible to guess within the window regardless, so a shared reverse-proxy
// IP or a fat-fingering operator isn't locked out for long.
const (
	loginMaxFailures = 10
	loginWindow      = time.Minute
	// minRemoteTokenLen is the shortest operator-chosen token accepted on a
	// non-loopback bind. Auto-generated loopback tokens are 64 hex chars and
	// exempt.
	minRemoteTokenLen = 16
)

// resolveAuthToken determines the shared secret. A configured token is
// expanded (${env:}/${file:}) and used as-is; an empty token is only reached
// on a loopback bind (validateBindSecurity guarantees this) and is
// auto-generated for one-click local access.
func resolveAuthToken(opts Options) (token string, autoGenerated bool, err error) {
	if strings.TrimSpace(opts.AuthToken) != "" {
		expanded, err := config.Expand(opts.AuthToken)
		if err != nil {
			return "", false, fmt.Errorf("webui: expanding --webui-auth-token: %w", err)
		}
		expanded = strings.TrimSpace(expanded)
		if expanded == "" {
			return "", false, fmt.Errorf("webui: --webui-auth-token expanded to an empty value")
		}
		return expanded, false, nil
	}
	tok, err := randomToken(32)
	if err != nil {
		return "", false, err
	}
	return tok, true, nil
}

// randomToken returns a hex-encoded cryptographically-random token.
func randomToken(nbytes int) (string, error) {
	b := make([]byte, nbytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("webui: generating random token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// tokenEqual compares two secrets in constant time.
func tokenEqual(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}

// bearerToken extracts a "Authorization: Bearer <token>" value.
func bearerToken(r *http.Request) (string, bool) {
	const prefix = "bearer "
	h := r.Header.Get("Authorization")
	if len(h) > len(prefix) && strings.EqualFold(h[:len(prefix)], prefix) {
		return h[len(prefix):], true
	}
	return "", false
}

// requireAuth wraps a handler so only authenticated requests reach it. A
// cookie-authed request also slides the session (server-side in valid(), and
// the browser cookie here) so an active operator's session doesn't expire
// mid-migration (#601).
func (s *Server) requireAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ok, sid := s.authenticated(r)
		if ok {
			if sid != "" {
				s.setSessionCookie(w, r, sid)
			}
			next.ServeHTTP(w, r)
			return
		}
		// Auth failed. Throttle brute-force on the bearer/cookie path with the
		// same limiter as login (#594) — but only when a credential was
		// actually presented; a plain unauthenticated request must not let a
		// third party lock others out, and is the common pre-login case.
		if credentialPresented(r) {
			ip := s.clientIP(r)
			if allowed, retryAfter := s.logins.allow(ip); !allowed {
				w.Header().Set("Retry-After", strconv.Itoa(int(retryAfter.Seconds())+1))
				writeError(w, http.StatusTooManyRequests, "rate_limited", "too many failed authentication attempts; try again shortly")
				return
			}
			n := s.logins.fail(ip)
			logging.WarnEvent("webui: failed auth", "remote", ip, "consecutive_failures", n)
		}
		writeError(w, http.StatusUnauthorized, "unauthorized", "authentication required")
	})
}

// credentialPresented reports whether the request carried a bearer token or a
// session cookie (valid or not) — i.e. an authentication attempt, as opposed
// to an anonymous request.
func credentialPresented(r *http.Request) bool {
	if _, ok := bearerToken(r); ok {
		return true
	}
	_, err := r.Cookie(sessionCookie)
	return err == nil
}

// authenticated accepts a valid browser session cookie or a matching bearer
// token (for curl/API clients). The returned sid is non-empty only for the
// cookie-session path, so the caller can slide the cookie.
func (s *Server) authenticated(r *http.Request) (bool, string) {
	if c, err := r.Cookie(sessionCookie); err == nil && s.sessions.valid(c.Value) {
		return true, c.Value
	}
	if tok, ok := bearerToken(r); ok && tokenEqual(tok, s.token) {
		return true, ""
	}
	return false, ""
}

// setSessionCookie (re)issues the session cookie with a fresh TTL. Shared by
// login and the per-request slide in requireAuth.
func (s *Server) setSessionCookie(w http.ResponseWriter, r *http.Request, sid string) {
	http.SetCookie(w, &http.Cookie{
		Name:     sessionCookie,
		Value:    sid,
		Path:     "/",
		HttpOnly: true,
		Secure:   requestIsHTTPS(r),
		SameSite: http.SameSiteStrictMode,
		MaxAge:   int(sessionTTL.Seconds()),
	})
}

// clientIP returns the IP dmt attributes a request to for rate-limiting and
// audit logging. By default that is the connecting peer (RemoteAddr) —
// X-Forwarded-For is client-spoofable, and trusting it blindly would let an
// attacker rotate the header to evade the login limiter. When
// --webui-trusted-proxy CIDRs are configured AND the peer falls inside one,
// the real client is recovered from X-Forwarded-For by walking right-to-left
// past any further trusted hops, so a reverse-proxy deployment gets per-client
// throttling without opening XFF spoofing (#604).
func (s *Server) clientIP(r *http.Request) string {
	peer := hostOnly(r.RemoteAddr)
	if len(s.trustedProxies) == 0 || !ipInNets(peer, s.trustedProxies) {
		return peer
	}
	parts := strings.Split(r.Header.Get("X-Forwarded-For"), ",")
	for i := len(parts) - 1; i >= 0; i-- {
		ip := strings.TrimSpace(parts[i])
		if ip == "" {
			continue
		}
		if ipInNets(ip, s.trustedProxies) {
			continue // another trusted hop; keep walking toward the client
		}
		return ip // first untrusted entry is the real client
	}
	return peer // XFF empty or only trusted proxies
}

// hostOnly strips the port from a host:port (RemoteAddr), tolerating a bare host.
func hostOnly(addr string) string {
	if host, _, err := net.SplitHostPort(addr); err == nil {
		return host
	}
	return addr
}

// handleLogin exchanges the shared token for a session cookie. The token is
// read from the JSON body {"token":"..."}. The loopback one-click link carries
// the token in the page URL, but the SPA forwards it here in the POST body —
// the token is never accepted as a query parameter, to keep it out of request
// logs and the server access path.
func (s *Server) handleLogin(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "method_not_allowed", "use POST")
		return
	}
	ip := s.clientIP(r)
	if ok, retryAfter := s.logins.allow(ip); !ok {
		w.Header().Set("Retry-After", strconv.Itoa(int(retryAfter.Seconds())+1))
		writeError(w, http.StatusTooManyRequests, "rate_limited", "too many failed login attempts; try again shortly")
		return
	}
	var body struct {
		Token string `json:"token"`
	}
	if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&body); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "expected JSON body {\"token\":\"…\"}")
		return
	}
	if body.Token == "" || !tokenEqual(body.Token, s.token) {
		n := s.logins.fail(ip)
		logging.WarnEvent("webui: failed login", "remote", ip, "consecutive_failures", n)
		writeError(w, http.StatusUnauthorized, "invalid_token", "invalid auth token")
		return
	}
	s.logins.reset(ip)
	sid, err := s.sessions.create()
	if err != nil {
		writeError(w, http.StatusInternalServerError, "session_error", "could not create session")
		return
	}
	s.setSessionCookie(w, r, sid)
	writeJSON(w, http.StatusOK, map[string]any{"status": "ok"})
}

// handleLogout clears the session server-side and expires the cookie.
func (s *Server) handleLogout(w http.ResponseWriter, r *http.Request) {
	if c, err := r.Cookie(sessionCookie); err == nil {
		s.sessions.destroy(c.Value)
	}
	http.SetCookie(w, &http.Cookie{
		Name:     sessionCookie,
		Value:    "",
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
		MaxAge:   -1,
	})
	writeJSON(w, http.StatusOK, map[string]any{"status": "ok"})
}

// sessionMaxLife caps a session's total lifetime regardless of sliding (#601
// review): even a continuously-renewed session (or a stolen cookie kept warm
// by requests) dies after this, forcing a fresh login. Set well above any
// realistic single-migration watch so it never interrupts legitimate use.
const sessionMaxLife = 7 * 24 * time.Hour

// sessionStore is an in-memory set of live session IDs with sliding idle
// expiry and an absolute lifetime cap. A single-operator, single-process store
// is sufficient for the local/remote operator tool; there is no multi-user or
// clustered requirement (see epic non-goals).
type sessionStore struct {
	mu  sync.Mutex
	m   map[string]sessionEntry
	ttl time.Duration
}

type sessionEntry struct {
	exp     time.Time // sliding idle expiry
	created time.Time // for the absolute lifetime cap
}

func newSessionStore(ttl time.Duration) *sessionStore {
	return &sessionStore{m: make(map[string]sessionEntry), ttl: ttl}
}

func (s *sessionStore) create() (string, error) {
	id, err := randomToken(32)
	if err != nil {
		return "", err
	}
	now := time.Now()
	s.mu.Lock()
	// Opportunistically prune expired sessions so the map can't grow
	// unbounded across a long-lived server's repeated logins (valid() only
	// evicts the id it happens to look up).
	for k, e := range s.m {
		if now.After(e.exp) || now.After(e.created.Add(sessionMaxLife)) {
			delete(s.m, k)
		}
	}
	s.m[id] = sessionEntry{exp: now.Add(s.ttl), created: now}
	s.mu.Unlock()
	return id, nil
}

// valid reports whether the session id is live, sliding its expiry forward on
// each successful check so an in-use session doesn't expire out from under an
// active operator (#601). A passively-watched migration keeps its session warm
// via the SPA heartbeat, which makes an authenticated request on an interval.
func (s *sessionStore) valid(id string) bool {
	if id == "" {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.m[id]
	if !ok {
		return false
	}
	now := time.Now()
	// Idle expiry or absolute lifetime cap both terminate the session.
	if now.After(e.exp) || now.After(e.created.Add(sessionMaxLife)) {
		delete(s.m, id)
		return false
	}
	// Slide the idle expiry, but never past the absolute cap.
	e.exp = now.Add(s.ttl)
	if cap := e.created.Add(sessionMaxLife); e.exp.After(cap) {
		e.exp = cap
	}
	s.m[id] = e
	return true
}

func (s *sessionStore) destroy(id string) {
	s.mu.Lock()
	delete(s.m, id)
	s.mu.Unlock()
}

// loginLimiter throttles brute-force attempts on /api/login, keyed by client
// IP (#594). After loginMaxFailures failures within loginWindow the IP is
// locked out for loginWindow; a successful login resets its bucket.
type loginLimiter struct {
	mu     sync.Mutex
	m      map[string]*loginAttempts
	max    int
	window time.Duration
}

type loginAttempts struct {
	fails       int
	first       time.Time
	lockedUntil time.Time
}

func newLoginLimiter() *loginLimiter {
	return &loginLimiter{m: make(map[string]*loginAttempts), max: loginMaxFailures, window: loginWindow}
}

// allow reports whether ip may attempt a login now. When locked, retryAfter is
// the remaining lockout duration.
func (l *loginLimiter) allow(ip string) (bool, time.Duration) {
	l.mu.Lock()
	defer l.mu.Unlock()
	a := l.m[ip]
	if a == nil {
		return true, 0
	}
	if d := time.Until(a.lockedUntil); d > 0 {
		return false, d
	}
	return true, 0
}

// fail records a failed attempt and returns the running failure count. When it
// reaches the max, the IP is locked for the window.
func (l *loginLimiter) fail(ip string) int {
	now := time.Now()
	l.mu.Lock()
	defer l.mu.Unlock()
	// Opportunistic prune of stale buckets so the map can't grow unbounded.
	for k, v := range l.m {
		if now.Sub(v.first) > l.window && now.After(v.lockedUntil) {
			delete(l.m, k)
		}
	}
	a := l.m[ip]
	if a == nil || now.Sub(a.first) > l.window {
		a = &loginAttempts{first: now}
		l.m[ip] = a
	}
	a.fails++
	if a.fails >= l.max {
		a.lockedUntil = now.Add(l.window)
	}
	return a.fails
}

// reset clears an IP's failure bucket after a successful login.
func (l *loginLimiter) reset(ip string) {
	l.mu.Lock()
	delete(l.m, ip)
	l.mu.Unlock()
}
