package webui

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// newTestServer builds a Server with a fixed token and no port bound.
func newTestServer(t *testing.T, opts Options) *Server {
	t.Helper()
	if opts.Addr == "" {
		opts.Addr = "127.0.0.1:0"
	}
	s, err := New(opts)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return s
}

func TestResolveAuthTokenAutoGenerated(t *testing.T) {
	tok, auto, err := resolveAuthToken(Options{Addr: "127.0.0.1:8484"})
	if err != nil {
		t.Fatalf("resolveAuthToken: %v", err)
	}
	if !auto {
		t.Error("expected auto-generated token for empty AuthToken")
	}
	if len(tok) != 64 { // 32 bytes hex
		t.Errorf("token length = %d, want 64", len(tok))
	}
}

func TestResolveAuthTokenExplicit(t *testing.T) {
	tok, auto, err := resolveAuthToken(Options{AuthToken: "  s3cret  "})
	if err != nil {
		t.Fatalf("resolveAuthToken: %v", err)
	}
	if auto {
		t.Error("explicit token should not be marked auto-generated")
	}
	if tok != "s3cret" {
		t.Errorf("token = %q, want trimmed %q", tok, "s3cret")
	}
}

func TestResolveAuthTokenExpandsEnv(t *testing.T) {
	t.Setenv("DMT_TEST_WEBUI_TOKEN", "from-env")
	tok, auto, err := resolveAuthToken(Options{AuthToken: "${env:DMT_TEST_WEBUI_TOKEN}"})
	if err != nil {
		t.Fatalf("resolveAuthToken: %v", err)
	}
	if auto || tok != "from-env" {
		t.Errorf("got token=%q auto=%v, want from-env/false", tok, auto)
	}
}

func TestTokenEqualConstantTime(t *testing.T) {
	if !tokenEqual("abc", "abc") {
		t.Error("equal tokens should match")
	}
	if tokenEqual("abc", "abd") {
		t.Error("different tokens should not match")
	}
	if tokenEqual("abc", "abcd") {
		t.Error("different-length tokens should not match")
	}
}

func TestLoginFlowSetsSessionCookie(t *testing.T) {
	s := newTestServer(t, Options{AuthToken: "topsecret"})
	h := s.buildHandler()

	// Wrong token → 401, no cookie.
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, "/api/login", strings.NewReader(`{"token":"nope"}`))
	req.Header.Set("Content-Type", "application/json")
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("bad-token login status = %d, want 401", rec.Code)
	}

	// Correct token → 200 + session cookie.
	rec = httptest.NewRecorder()
	req = httptest.NewRequest(http.MethodPost, "/api/login", strings.NewReader(`{"token":"topsecret"}`))
	req.Header.Set("Content-Type", "application/json")
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("good-token login status = %d, want 200", rec.Code)
	}
	cookie := sessionCookieFrom(rec.Result().Cookies())
	if cookie == nil {
		t.Fatal("expected session cookie after login")
	}
	if !cookie.HttpOnly || cookie.SameSite != http.SameSiteStrictMode {
		t.Errorf("cookie flags weak: HttpOnly=%v SameSite=%v", cookie.HttpOnly, cookie.SameSite)
	}

	// Cookie authenticates /api/health.
	rec = httptest.NewRecorder()
	req = httptest.NewRequest(http.MethodGet, "/api/health", nil)
	req.AddCookie(cookie)
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("authenticated health status = %d, want 200", rec.Code)
	}
	var body map[string]any
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("health body: %v", err)
	}
	if body["status"] != "ok" {
		t.Errorf("health status field = %v, want ok", body["status"])
	}
}

func TestHealthRequiresAuth(t *testing.T) {
	s := newTestServer(t, Options{AuthToken: "topsecret"})
	h := s.buildHandler()

	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/api/health", nil))
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("unauthenticated health status = %d, want 401", rec.Code)
	}
}

func TestBearerTokenAuth(t *testing.T) {
	s := newTestServer(t, Options{AuthToken: "topsecret"})
	h := s.buildHandler()

	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/api/health", nil)
	req.Header.Set("Authorization", "Bearer topsecret")
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("bearer health status = %d, want 200", rec.Code)
	}

	rec = httptest.NewRecorder()
	req = httptest.NewRequest(http.MethodGet, "/api/health", nil)
	req.Header.Set("Authorization", "Bearer wrong")
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("wrong bearer status = %d, want 401", rec.Code)
	}
}

func TestLogoutInvalidatesSession(t *testing.T) {
	s := newTestServer(t, Options{AuthToken: "topsecret"})
	sid, err := s.sessions.create()
	if err != nil {
		t.Fatalf("create session: %v", err)
	}
	if !s.sessions.valid(sid) {
		t.Fatal("session should be valid after create")
	}
	h := s.buildHandler()
	rec := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, "/api/logout", nil)
	req.AddCookie(&http.Cookie{Name: sessionCookie, Value: sid})
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("logout status = %d, want 200", rec.Code)
	}
	if s.sessions.valid(sid) {
		t.Error("session should be invalid after logout")
	}
}

func TestSessionExpiry(t *testing.T) {
	store := newSessionStore(-1 * time.Second) // already expired on create
	sid, err := store.create()
	if err != nil {
		t.Fatalf("create: %v", err)
	}
	if store.valid(sid) {
		t.Error("expired session should not be valid")
	}
}

func sessionCookieFrom(cookies []*http.Cookie) *http.Cookie {
	for _, c := range cookies {
		if c.Name == sessionCookie {
			return c
		}
	}
	return nil
}
