package webui

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/johndauphine/dmt/internal/config"
)

// sessionCookie names the browser session cookie set after a successful login.
const sessionCookie = "dmt_webui_session"

// resolveAuthToken determines the shared secret. A configured token is
// expanded (${env:}/${file:}) and used as-is; an empty token is only reached
// on a loopback bind (validateBindSecurity guarantees this) and is
// auto-generated for one-click local access.
func resolveAuthToken(opts Options) (token string, autoGenerated bool, err error) {
	if strings.TrimSpace(opts.AuthToken) != "" {
		expanded, err := config.Expand(opts.AuthToken)
		if err != nil {
			return "", false, fmt.Errorf("webui: expanding --webui-auth-token: %w", err)
		}
		expanded = strings.TrimSpace(expanded)
		if expanded == "" {
			return "", false, fmt.Errorf("webui: --webui-auth-token expanded to an empty value")
		}
		return expanded, false, nil
	}
	tok, err := randomToken(32)
	if err != nil {
		return "", false, err
	}
	return tok, true, nil
}

// randomToken returns a hex-encoded cryptographically-random token.
func randomToken(nbytes int) (string, error) {
	b := make([]byte, nbytes)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("webui: generating random token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// tokenEqual compares two secrets in constant time.
func tokenEqual(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}

// bearerToken extracts a "Authorization: Bearer <token>" value.
func bearerToken(r *http.Request) (string, bool) {
	const prefix = "bearer "
	h := r.Header.Get("Authorization")
	if len(h) > len(prefix) && strings.EqualFold(h[:len(prefix)], prefix) {
		return h[len(prefix):], true
	}
	return "", false
}

// requireAuth wraps a handler so only authenticated requests reach it.
func (s *Server) requireAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if s.authenticated(r) {
			next.ServeHTTP(w, r)
			return
		}
		writeError(w, http.StatusUnauthorized, "unauthorized", "authentication required")
	})
}

// authenticated accepts a valid browser session cookie or a matching bearer
// token (for curl/API clients).
func (s *Server) authenticated(r *http.Request) bool {
	if c, err := r.Cookie(sessionCookie); err == nil && s.sessions.valid(c.Value) {
		return true
	}
	if tok, ok := bearerToken(r); ok && tokenEqual(tok, s.token) {
		return true
	}
	return false
}

// handleLogin exchanges the shared token for a session cookie. The token is
// read from the JSON body {"token":"..."} or, for the loopback one-click link,
// a ?token= query parameter.
func (s *Server) handleLogin(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "method_not_allowed", "use POST")
		return
	}
	token := r.URL.Query().Get("token")
	if token == "" {
		var body struct {
			Token string `json:"token"`
		}
		if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&body); err == nil {
			token = body.Token
		}
	}
	if token == "" || !tokenEqual(token, s.token) {
		writeError(w, http.StatusUnauthorized, "invalid_token", "invalid auth token")
		return
	}
	sid, err := s.sessions.create()
	if err != nil {
		writeError(w, http.StatusInternalServerError, "session_error", "could not create session")
		return
	}
	http.SetCookie(w, &http.Cookie{
		Name:     sessionCookie,
		Value:    sid,
		Path:     "/",
		HttpOnly: true,
		Secure:   s.opts.tlsEnabled(),
		SameSite: http.SameSiteStrictMode,
		MaxAge:   int(sessionTTL.Seconds()),
	})
	writeJSON(w, http.StatusOK, map[string]any{"status": "ok"})
}

// handleLogout clears the session server-side and expires the cookie.
func (s *Server) handleLogout(w http.ResponseWriter, r *http.Request) {
	if c, err := r.Cookie(sessionCookie); err == nil {
		s.sessions.destroy(c.Value)
	}
	http.SetCookie(w, &http.Cookie{
		Name:     sessionCookie,
		Value:    "",
		Path:     "/",
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
		MaxAge:   -1,
	})
	writeJSON(w, http.StatusOK, map[string]any{"status": "ok"})
}

// sessionStore is an in-memory set of live session IDs with TTL expiry. A
// single-operator, single-process store is sufficient for the local/remote
// operator tool; there is no multi-user or clustered requirement (see epic
// non-goals).
type sessionStore struct {
	mu  sync.Mutex
	m   map[string]time.Time
	ttl time.Duration
}

func newSessionStore(ttl time.Duration) *sessionStore {
	return &sessionStore{m: make(map[string]time.Time), ttl: ttl}
}

func (s *sessionStore) create() (string, error) {
	id, err := randomToken(32)
	if err != nil {
		return "", err
	}
	s.mu.Lock()
	s.m[id] = time.Now().Add(s.ttl)
	s.mu.Unlock()
	return id, nil
}

func (s *sessionStore) valid(id string) bool {
	if id == "" {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	exp, ok := s.m[id]
	if !ok {
		return false
	}
	if time.Now().After(exp) {
		delete(s.m, id)
		return false
	}
	return true
}

func (s *sessionStore) destroy(id string) {
	s.mu.Lock()
	delete(s.m, id)
	s.mu.Unlock()
}
